import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, ThemeProvider } from 'md3-react'
// import { AdaptiveProvider, Button, ThemeProvider, ThemeTokens } from '@znui/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (


    <ThemeProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button>Enabled</Button>
      {/* <h1 style={{ color: ThemeTokens.error }}>AA</h1> */}
    </ThemeProvider>


  )
}
